title: Hello, I'm Alexander Zagaynov
email: zalex80@gmail.com
description: >
  Hello, I'm Alexander Zagaynov,
  and this is my personal blog.

url: https://alexanderzagaynov.com
permalink: :title

github_username:  AlexanderZagaynov
linkedin_username: zalex80

markdown: kramdown

kramdown:
  input: GFM

defaults:
  -
    scope:
      type: pages
    values:
      layout: page
  -
    scope:
      type: posts
    values:
      layout: post
  # -
  #   scope:
  #     type: archive
  #   values:
  #     layout: post
