title: Alexander Zagaynov
email: zalex80@gmail.com
description: >
  Hello! My name is Alexander Zagaynov, and I write here about my experience
  acquirements in the field of web development and a tied-up technologies.
  Please feel free to contact me with questions and offers in any convenient way.

url: http://alexanderzagaynov.com
permalink: :title

twitter_username: yafduch
github_username:  zalex80

markdown: kramdown

defaults:
  -
    scope:
      type: posts
    values:
      layout: post
  -
    scope:
      type: pages
    values:
      layout: page
